// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: auth_token.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAuthToken = `-- name: CreateAuthToken :one
INSERT INTO auth_tokens (user_id, token, expires_at)
VALUES ($1, $2, $3)
RETURNING id, user_id, token, expires_at, created_at
`

type CreateAuthTokenParams struct {
	UserID    pgtype.Int4      `json:"user_id"`
	Token     string           `json:"token"`
	ExpiresAt pgtype.Timestamp `json:"expires_at"`
}

func (q *Queries) CreateAuthToken(ctx context.Context, arg CreateAuthTokenParams) (AuthToken, error) {
	row := q.db.QueryRow(ctx, createAuthToken, arg.UserID, arg.Token, arg.ExpiresAt)
	var i AuthToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAllAuthTokens = `-- name: DeleteAllAuthTokens :exec
DELETE FROM auth_tokens WHERE user_id = $1
`

func (q *Queries) DeleteAllAuthTokens(ctx context.Context, userID pgtype.Int4) error {
	_, err := q.db.Exec(ctx, deleteAllAuthTokens, userID)
	return err
}

const deleteAuthToken = `-- name: DeleteAuthToken :exec
DELETE FROM auth_tokens WHERE user_id = $1 AND token = $2
`

type DeleteAuthTokenParams struct {
	UserID pgtype.Int4 `json:"user_id"`
	Token  string      `json:"token"`
}

func (q *Queries) DeleteAuthToken(ctx context.Context, arg DeleteAuthTokenParams) error {
	_, err := q.db.Exec(ctx, deleteAuthToken, arg.UserID, arg.Token)
	return err
}

const validateAuthToken = `-- name: ValidateAuthToken :one
SELECT id, user_id, token, expires_at, created_at FROM auth_tokens
WHERE user_id = $1 AND token = $2 AND expires_at > NOW()
`

type ValidateAuthTokenParams struct {
	UserID pgtype.Int4 `json:"user_id"`
	Token  string      `json:"token"`
}

func (q *Queries) ValidateAuthToken(ctx context.Context, arg ValidateAuthTokenParams) (AuthToken, error) {
	row := q.db.QueryRow(ctx, validateAuthToken, arg.UserID, arg.Token)
	var i AuthToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}
