// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: cart.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addToCart = `-- name: AddToCart :exec
INSERT INTO cart_items (cart_id, product_id, quantity)
VALUES ($1, $2, $3)
ON CONFLICT (cart_id, product_id)
    DO UPDATE SET quantity = cart_items.quantity + EXCLUDED.quantity
`

type AddToCartParams struct {
	CartID    pgtype.Int4 `json:"cart_id"`
	ProductID pgtype.Int4 `json:"product_id"`
	Quantity  int32       `json:"quantity"`
}

func (q *Queries) AddToCart(ctx context.Context, arg AddToCartParams) error {
	_, err := q.db.Exec(ctx, addToCart, arg.CartID, arg.ProductID, arg.Quantity)
	return err
}

const clearCart = `-- name: ClearCart :exec
DELETE FROM cart_items WHERE cart_id = $1
`

func (q *Queries) ClearCart(ctx context.Context, cartID pgtype.Int4) error {
	_, err := q.db.Exec(ctx, clearCart, cartID)
	return err
}

const createCart = `-- name: CreateCart :one
INSERT INTO carts (user_id)
VALUES ($1)
RETURNING id, user_id, created_at
`

func (q *Queries) CreateCart(ctx context.Context, userID pgtype.Int4) (Cart, error) {
	row := q.db.QueryRow(ctx, createCart, userID)
	var i Cart
	err := row.Scan(&i.ID, &i.UserID, &i.CreatedAt)
	return i, err
}

const getCart = `-- name: GetCart :many
SELECT ci.id, ci.cart_id, ci.product_id, ci.quantity, ci.added_at,
       p.name AS product_name, p.price AS product_price
FROM cart_items ci
         JOIN products p ON ci.product_id = p.id
WHERE ci.cart_id = $1
`

type GetCartRow struct {
	ID           int32            `json:"id"`
	CartID       pgtype.Int4      `json:"cart_id"`
	ProductID    pgtype.Int4      `json:"product_id"`
	Quantity     int32            `json:"quantity"`
	AddedAt      pgtype.Timestamp `json:"added_at"`
	ProductName  string           `json:"product_name"`
	ProductPrice pgtype.Numeric   `json:"product_price"`
}

func (q *Queries) GetCart(ctx context.Context, cartID pgtype.Int4) ([]GetCartRow, error) {
	rows, err := q.db.Query(ctx, getCart, cartID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCartRow{}
	for rows.Next() {
		var i GetCartRow
		if err := rows.Scan(
			&i.ID,
			&i.CartID,
			&i.ProductID,
			&i.Quantity,
			&i.AddedAt,
			&i.ProductName,
			&i.ProductPrice,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCartByUser = `-- name: GetCartByUser :one
SELECT id, user_id, created_at
FROM carts
WHERE user_id = $1
LIMIT 1
`

func (q *Queries) GetCartByUser(ctx context.Context, userID pgtype.Int4) (Cart, error) {
	row := q.db.QueryRow(ctx, getCartByUser, userID)
	var i Cart
	err := row.Scan(&i.ID, &i.UserID, &i.CreatedAt)
	return i, err
}
