// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Cart struct {
	ID        int32            `json:"id"`
	UserID    pgtype.Int4      `json:"user_id"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type CartItem struct {
	ID        int32            `json:"id"`
	CartID    pgtype.Int4      `json:"cart_id"`
	ProductID pgtype.Int4      `json:"product_id"`
	Quantity  int32            `json:"quantity"`
	AddedAt   pgtype.Timestamp `json:"added_at"`
}

type Category struct {
	ID       int32       `json:"id"`
	Name     string      `json:"name"`
	ParentID pgtype.Int4 `json:"parent_id"`
}

type Inventory struct {
	ProductID   int32            `json:"product_id"`
	Stock       int32            `json:"stock"`
	LastUpdated pgtype.Timestamp `json:"last_updated"`
}

type Order struct {
	ID         int32            `json:"id"`
	UserID     pgtype.Int4      `json:"user_id"`
	TotalPrice pgtype.Numeric   `json:"total_price"`
	Status     string           `json:"status"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
	UpdatedAt  pgtype.Timestamp `json:"updated_at"`
}

type OrderItem struct {
	ID        int32          `json:"id"`
	OrderID   pgtype.Int4    `json:"order_id"`
	ProductID pgtype.Int4    `json:"product_id"`
	Quantity  int32          `json:"quantity"`
	Price     pgtype.Numeric `json:"price"`
	Subtotal  pgtype.Numeric `json:"subtotal"`
}

type Payment struct {
	ID            int32            `json:"id"`
	OrderID       pgtype.Int4      `json:"order_id"`
	UserID        pgtype.Int4      `json:"user_id"`
	Amount        pgtype.Numeric   `json:"amount"`
	Status        string           `json:"status"`
	TransactionID pgtype.Text      `json:"transaction_id"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
}

type Product struct {
	ID          int32            `json:"id"`
	Name        string           `json:"name"`
	Description pgtype.Text      `json:"description"`
	Price       pgtype.Numeric   `json:"price"`
	Stock       int32            `json:"stock"`
	ImageUrl    pgtype.Text      `json:"image_url"`
	CategoryID  pgtype.Int4      `json:"category_id"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

type Role struct {
	ID          int32       `json:"id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
}

type Session struct {
	ID           uuid.UUID `json:"id"`
	UserID       int32     `json:"user_id"`
	RefreshToken string    `json:"refresh_token"`
	UserAgent    string    `json:"user_agent"`
	ClientIp     string    `json:"client_ip"`
	IsBlocked    bool      `json:"is_blocked"`
	ExpiresAt    time.Time `json:"expires_at"`
	CreatedAt    time.Time `json:"created_at"`
}

type User struct {
	ID           int32            `json:"id"`
	Email        string           `json:"email"`
	PasswordHash string           `json:"password_hash"`
	FullName     pgtype.Text      `json:"full_name"`
	AvatarUrl    pgtype.Text      `json:"avatar_url"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
	Role         string           `json:"role"`
}

type UserRole struct {
	UserID int32 `json:"user_id"`
	RoleID int32 `json:"role_id"`
}
