// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: order.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelOrder = `-- name: CancelOrder :exec
UPDATE orders
SET status = 'cancelled', updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND status = 'pending'
`

func (q *Queries) CancelOrder(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, cancelOrder, id)
	return err
}

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (user_id, total_price, status)
VALUES ($1, $2, 'pending')
RETURNING id, created_at
`

type CreateOrderParams struct {
	UserID     pgtype.Int4    `json:"user_id"`
	TotalPrice pgtype.Numeric `json:"total_price"`
}

type CreateOrderRow struct {
	ID        int32            `json:"id"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (CreateOrderRow, error) {
	row := q.db.QueryRow(ctx, createOrder, arg.UserID, arg.TotalPrice)
	var i CreateOrderRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const settleOrder = `-- name: SettleOrder :exec
UPDATE orders
SET status = 'paid', updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND status = 'pending'
`

func (q *Queries) SettleOrder(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, settleOrder, id)
	return err
}

const updateOrder = `-- name: UpdateOrder :exec
UPDATE orders
SET total_price = $1, status = $2, updated_at = CURRENT_TIMESTAMP
WHERE id = $3 AND status NOT IN ('shipped', 'completed', 'cancelled')
`

type UpdateOrderParams struct {
	TotalPrice pgtype.Numeric `json:"total_price"`
	Status     string         `json:"status"`
	ID         int32          `json:"id"`
}

func (q *Queries) UpdateOrder(ctx context.Context, arg UpdateOrderParams) error {
	_, err := q.db.Exec(ctx, updateOrder, arg.TotalPrice, arg.Status, arg.ID)
	return err
}
