// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: order_items.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOrderItem = `-- name: CreateOrderItem :exec
INSERT INTO order_items (order_id, product_id, quantity, price, subtotal)
VALUES ($1, $2, $3, $4, $5)
`

type CreateOrderItemParams struct {
	OrderID   pgtype.Int4    `json:"order_id"`
	ProductID pgtype.Int4    `json:"product_id"`
	Quantity  int32          `json:"quantity"`
	Price     pgtype.Numeric `json:"price"`
	Subtotal  pgtype.Numeric `json:"subtotal"`
}

func (q *Queries) CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) error {
	_, err := q.db.Exec(ctx, createOrderItem,
		arg.OrderID,
		arg.ProductID,
		arg.Quantity,
		arg.Price,
		arg.Subtotal,
	)
	return err
}

const getOrderItemsByOrderID = `-- name: GetOrderItemsByOrderID :many
SELECT product_id, quantity, price
FROM order_items
WHERE order_id = $1
`

type GetOrderItemsByOrderIDRow struct {
	ProductID pgtype.Int4    `json:"product_id"`
	Quantity  int32          `json:"quantity"`
	Price     pgtype.Numeric `json:"price"`
}

func (q *Queries) GetOrderItemsByOrderID(ctx context.Context, orderID pgtype.Int4) ([]GetOrderItemsByOrderIDRow, error) {
	rows, err := q.db.Query(ctx, getOrderItemsByOrderID, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetOrderItemsByOrderIDRow{}
	for rows.Next() {
		var i GetOrderItemsByOrderIDRow
		if err := rows.Scan(&i.ProductID, &i.Quantity, &i.Price); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
