// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: payment.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelPayment = `-- name: CancelPayment :exec
UPDATE payments
SET status = 'cancelled', updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND status = 'pending'
`

func (q *Queries) CancelPayment(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, cancelPayment, id)
	return err
}

const confirmPayment = `-- name: ConfirmPayment :exec
UPDATE payments
SET status = 'success', updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND status = 'pending'
`

func (q *Queries) ConfirmPayment(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, confirmPayment, id)
	return err
}

const createPayment = `-- name: CreatePayment :one
INSERT INTO payments (order_id, user_id, amount, status, transaction_id)
VALUES ($1, $2, $3, 'pending', $4)
RETURNING id, created_at
`

type CreatePaymentParams struct {
	OrderID       pgtype.Int4    `json:"order_id"`
	UserID        pgtype.Int4    `json:"user_id"`
	Amount        pgtype.Numeric `json:"amount"`
	TransactionID pgtype.Text    `json:"transaction_id"`
}

type CreatePaymentRow struct {
	ID        int32            `json:"id"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (CreatePaymentRow, error) {
	row := q.db.QueryRow(ctx, createPayment,
		arg.OrderID,
		arg.UserID,
		arg.Amount,
		arg.TransactionID,
	)
	var i CreatePaymentRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const timeoutPayment = `-- name: TimeoutPayment :exec
UPDATE payments
SET status = 'cancelled', updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND status = 'pending' AND created_at < NOW() - INTERVAL '15 minutes'
`

func (q *Queries) TimeoutPayment(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, timeoutPayment, id)
	return err
}
