// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddToCart(ctx context.Context, arg AddToCartParams) error
	AssignRoleToUser(ctx context.Context, arg AssignRoleToUserParams) error
	CancelOrder(ctx context.Context, id int32) error
	CancelPayment(ctx context.Context, id int32) error
	ClearCart(ctx context.Context, cartID pgtype.Int4) error
	ConfirmPayment(ctx context.Context, id int32) error
	CreateCart(ctx context.Context, userID pgtype.Int4) (Cart, error)
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error)
	CreateOrder(ctx context.Context, arg CreateOrderParams) (CreateOrderRow, error)
	CreatePayment(ctx context.Context, arg CreatePaymentParams) (CreatePaymentRow, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteCategory(ctx context.Context, id int32) error
	DeleteProduct(ctx context.Context, id int32) error
	DeleteUser(ctx context.Context, id int32) error
	GetCart(ctx context.Context, cartID pgtype.Int4) ([]GetCartRow, error)
	GetCartByUser(ctx context.Context, userID pgtype.Int4) (Cart, error)
	GetCategoryByID(ctx context.Context, id int32) (Category, error)
	GetProductByID(ctx context.Context, id int32) (Product, error)
	GetRoleByName(ctx context.Context, name string) (Role, error)
	GetSession(ctx context.Context, id uuid.UUID) (Session, error)
	GetSubcategories(ctx context.Context, parentID pgtype.Int4) ([]Category, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id int32) (interface{}, error)
	GetUserRoles(ctx context.Context, userID int32) ([]string, error)
	ListCategories(ctx context.Context) ([]Category, error)
	ListProducts(ctx context.Context, arg ListProductsParams) ([]Product, error)
	ListRoles(ctx context.Context) ([]Role, error)
	RemoveUserRole(ctx context.Context, arg RemoveUserRoleParams) error
	SettleOrder(ctx context.Context, id int32) error
	TimeoutPayment(ctx context.Context, id int32) error
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error)
	UpdateOrder(ctx context.Context, arg UpdateOrderParams) error
	UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error)
}

var _ Querier = (*Queries)(nil)
